### ISSUE TITLE
Webjar

### ISSUE THREAD

**Issue by omidb** [cpettitt/dagre#179]
Hi,

I found a webjar for [dagre-d3](https://github.com/webjars/dagre-d3). Is it possible for you to do the same for dagre.js .

Thanks

**Comment by cpettitt** [comment]
I welcome someone from the community to contribute this. I don't have a use case for it and don't know the best practices, so I'm not the best person to do this.

**Comment by omidb** [comment]
Apparently here is the properties for dagre webjar:

GroupID = org.webjars.bower
ArtifactID = dagre
Version = 0.7.2
