### ISSUE TITLE
How can I get/set edge labels?

### ISSUE THREAD

**Issue by omidb** [cpettitt/dagre#180]
Hi,

I couldn't find anything in WIKI that shows how I should set a label for edge and get the position of a label. Would you please help me with that?

thanks

**Comment by cpettitt** [comment]
To set an edge label:

```
g.setEdge("kspacey",   "swilliams", { label: "foo" });
```

To get the position of  label:

```
var x = g.edge("kspacey", "swilliams").x;
var y = g.edge("kspacey", "swilliams").y;
```

Updated the wiki to specify `x` and `y` attributes for edges.

**Comment by omidb** [comment]
@cpettitt  thanks Chris, I tried these, but it's none of them work:
```javascript
g.edge("kspacey", "swilliams").x;
>undefined
g.edge({v:"kspacey", w:"swilliams"}).x;
>undefined
```

**Comment by omidb** [comment]
@cpettitt Would you please take a look at this?

**Comment by Batistleman** [comment]
The label also needs a height and a width:

    g.setEdge('a', 'b', { label: "foo" , width: 100, height: 20})
