### ISSUE TITLE
Edge x/y not calculated

### ISSUE THREAD

**Issue by dennisschumann** [cpettitt/dagre#208]
Hello,

what do I have to change on the example from the wiki to force Dagre.js to calculate the edge x/y as described in the wiki (for positioning the label). I only get the points for the edges.

Thank you and best regards!

**Comment by AlexanderSuv** [comment]
Hi,
you need to set edge\`s label width and height like you do it for the node\`s one:
```g.setEdge("kspacey",   "swilliams", { width: '10', height: '10' });```
