### ISSUE TITLE
No compiled files in v0.0.1~v0.5.4

### ISSUE THREAD

**Issue by dakshshah96** [cpettitt/dagre#214]
Hey @cpettitt,

I'd like to host your library, dagre on [cdnjs](https://github.com/cdnjs/cdnjs) — It is one of the most famous free and public web front-end CDN services which is used by [~1,143,000 websites](https://trends.builtwith.com/cdn/CDN-JS) worldwide.

However, I noticed that for v0.0.1~v0.5.4, final ready-to-use compiled files haven't been included in the repository. What do you think should be done regarding those?

* We don't host the old versions
* The compiled files exist but I somehow overlooked them
* Maybe you provide the compiled files for the above mentioned versions

[cdnjs/cdnjs/11141](https://github.com/cdnjs/cdnjs/pull/11141)

**Comment by cpettitt** [comment]
I would suggest ignoring those versions. They had a different API and the current release has been out for a couple of years now - crazy to realize it has been that long!

If you really want them you could recreate them from tags in the source.

**Comment by dakshshah96** [comment]
Thanks for the response @cpettitt!
