### ISSUE TITLE
Interacting with Graph Elements

### ISSUE THREAD

**Issue by AlbertoCastelo** [cpettitt/dagre#218]
Hi,

is there a way I can do some interaction with graph elements, such click in a node to display some information?

**Comment by fdlk** [comment]
Disclaimer: I've just started using this library.
But I think that dagre only does the layout, so how you interact with the graph elements depends on how you render them.

**Comment by AlbertoCastelo** [comment]
Yes you're right. In his dagre-d3.js he has an example on how to do "hovering interaction"
